const MethodName = {
  0: "JAFARI",
  1: "KARACHI",
  2: "ISNA",
  3: "MWL",
  4: "MAKKAH",
  5: "EGYPT",
  7: "TEHRAN",
  8: "GULF",
  9: "KUWAIT",
  10: "QATAR",
  11: "SINGAPORE",
  12: "FRANCE",
  13: "TURKEY",
  14: "RUSSIA",
  15: "MOONSIGHTING",
  16: "DUBAI",
  17: "JAKIM",
  18: "TUNISIA",
  19: "ALGERIA",
  20: "KEMENAG",
  21: "MOROCCO",
  22: "PORTUGAL",
  23: "JORDAN",
  99: "CUSTOM",
};
module.exports = MethodName;
