//! SOON
export type QuranLanguage =
  | "ar"
  | "am"
  | "az"
  | "ber"
  | "bn"
  | "cs"
  | "ce"
  | "de"
  | "dv"
  | "en"
  | "es"
  | "fa"
  | "fr"
  | "ha"
  | "hi"
  | "id"
  | "it"
  | "ja"
  | "ko"
  | "ku"
  | "ml"
  | "nl"
  | "no"
  | "pl"
  | "ps"
  | "pt"
  | "ro"
  | "ru"
  | "sd"
  | "so"
  | "sq"
  | "sv"
  | "sw"
  | "ta"
  | "tg"
  | "th"
  | "tr"
  | "tt"
  | "ug"
  | "ur"
  | "uz";

//! SOON
export type QuranIdentifier =
  | "ar.muyassar"
  | "az.mammadaliyev"
  | "az.musayev"
  | "bn.bengali"
  | "cs.hrbek"
  | "cs.nykl"
  | "de.aburida"
  | "de.bubenheim"
  | "de.khoury"
  | "de.zaidan"
  | "dv.divehi"
  | "en.ahmedali"
  | "en.ahmedraza"
  | "en.arberry"
  | "en.asad"
  | "en.daryabadi"
  | "en.hilali"
  | "en.pickthall"
  | "en.qaribullah"
  | "en.sahih"
  | "en.sarwar"
  | "en.yusufali"
  | "fa.ayati"
  | "fa.fooladvand"
  | "fa.ghomshei"
  | "fa.makarem"
  | "fr.hamidullah"
  | "ha.gumi"
  | "hi.hindi"
  | "id.indonesian"
  | "it.piccardo"
  | "ja.japanese"
  | "ko.korean"
  | "ku.asan"
  | "ml.abdulhameed"
  | "nl.keyzer"
  | "no.berg"
  | "pl.bielawskiego"
  | "pt.elhayek"
  | "ro.grigore"
  | "ru.kuliev"
  | "ru.osmanov"
  | "ru.porokhova"
  | "sd.amroti"
  | "so.abduh"
  | "sq.ahmeti"
  | "sq.mehdiu"
  | "sq.nahi"
  | "sv.bernstrom"
  | "sw.barwani"
  | "ta.tamil"
  | "tg.ayati"
  | "th.thai"
  | "tr.ates"
  | "tr.bulac"
  | "tr.diyanet"
  | "tr.golpinarli"
  | "tr.ozturk"
  | "tr.transliteration"
  | "tr.vakfi"
  | "tr.yazir"
  | "tr.yildirim"
  | "tr.yuksel"
  | "tt.nugman"
  | "ug.saleh"
  | "ur.ahmedali"
  | "ur.jalandhry"
  | "ur.jawadi"
  | "ur.kanzuliman"
  | "ur.qadri"
  | "uz.sodik"
  | "en.maududi"
  | "en.shakir"
  | "en.transliteration"
  | "es.cortes"
  | "fa.ansarian"
  | "quran-simple"
  | "quran-simple-clean"
  | "quran-simple-enhanced"
  | "quran-simple-min"
  | "quran-uthmani-min"
  | "quran-uthmani"
  | "bg.theophanov"
  | "bs.mlivo"
  | "fa.bahrampour"
  | "es.asad"
  | "fa.khorramshahi"
  | "fa.mojtabavi"
  | "hi.farooq"
  | "id.muntakhab"
  | "ms.basmeih"
  | "ru.abuadel"
  | "ru.krachkovsky"
  | "ru.muntahab"
  | "ru.sablukov"
  | "ur.junagarhi"
  | "ur.maududi"
  | "zh.jian"
  | "zh.majian"
  | "fa.khorramdel"
  | "fa.moezzi"
  | "bs.korkut"
  | "ar.jalalayn"
  | "quran-tajweed"
  | "quran-wordbyword"
  | "ar.abdulbasitmurattal"
  | "ar.abdullahbasfar"
  | "ar.abdurrahmaansudais"
  | "ar.abdulsamad"
  | "ar.shaatree"
  | "ar.ahmedajamy"
  | "ar.alafasy"
  | "ar.hanirifai"
  | "ar.husary"
  | "ar.husarymujawwad"
  | "ar.hudhaify"
  | "ar.ibrahimakhbar"
  | "ar.mahermuaiqly"
  | "ar.minshawi"
  | "ar.minshawimujawwad"
  | "ar.muhammadayyoub"
  | "ar.muhammadjibreel"
  | "ar.saoodshuraym"
  | "en.walk"
  | "fa.hedayatfarfooladvand"
  | "ar.parhizgar"
  | "ur.khan"
  | "zh.chinese"
  | "fr.leclerc"
  | "quran-kids"
  | "quran-corpus-qd"
  | "si.naseemismail"
  | "quran-buck"
  | "zh.mazhonggang"
  | "ar.aymanswoaid"
  | "quran-wordbyword-2"
  | "quran-unicode"
  | "quran-uthmani-quran-academy"
  | "ba.mehanovic"
  | "ru.kuliev-audio"
  | "en.itani"
  | "ar.qurtubi"
  | "ar.miqbas"
  | "ar.waseet"
  | "ar.baghawi"
  | "my.ghazi"
  | "en.mubarakpuri"
  | "am.sadiq"
  | "ber.mensur"
  | "bn.hoque"
  | "en.qarai"
  | "en.wahiduddin"
  | "es.bornez"
  | "es.garcia"
  | "ur.najafi"
  | "fa.gharaati"
  | "fa.sadeqi"
  | "fa.safavi"
  | "id.jalalayn"
  | "ml.karakunnu"
  | "nl.leemhuis"
  | "nl.siregar"
  | "ps.abdulwali"
  | "ru.kuliev-alsaadi"
  | "ru.kuliev-audio-2"
  | "ce.magomedov"
  | "ru.transliteration";

//! SOON








//! SOON
export type QuranNames =
  | "تفسير المیسر"
  | "Məmmədəliyev & Bünyadov"
  | "Musayev"
  | "মুহিউদ্দীন খান"
  | "Hrbek"
  | "Nykl"
  | "Abu Rida"
  | "Bubenheim & Elyas"
  | "Khoury"
  | "Zaidan"
  | "ދިވެހި"
  | "Ahmed Ali"
  | "Ahmed Raza Khan"
  | "Arberry"
  | "Asad"
  | "Daryabadi"
  | "Hilali & Khan"
  | "Pickthall"
  | "Qaribullah & Darwish"
  | "Saheeh International"
  | "Sarwar"
  | "Yusuf Ali"
  | "آیتی"
  | "فولادوند"
  | "الهی قمشه‌ای"
  | "مکارم شیرازی"
  | "Hamidullah"
  | "Gumi"
  | "फ़ारूक़ ख़ान & नदवी"
  | "Bahasa Indonesia"
  | "Piccardo"
  | "Japanese"
  | "Korean"
  | "ته‌فسیری ئاسان"
  | "അബ്ദുല്‍ ഹമീദ് & പറപ്പൂര്‍"
  | "Keyzer"
  | "Einar Berg"
  | "Bielawskiego"
  | "El-Hayek"
  | "Grigore"
  | "Кулиев"
  | "Османов"
  | "Порохова"
  | "امروٽي"
  | "Abduh"
  | "Sherif Ahmeti"
  | "Feti Mehdiu"
  | "Efendi Nahi"
  | "Bernström"
  | "Al-Barwani"
  | "ஜான் டிரஸ்ட்"
  | "Оятӣ"
  | "ภาษาไทย"
  | "Süleyman Ateş"
  | "Alİ Bulaç"
  | "Diyanet İşleri"
  | "Abdulbakî Gölpınarlı"
  | "Öztürk"
  | "Çeviriyazı"
  | "Diyanet Vakfı"
  | "Elmalılı Hamdi Yazır"
  | "Suat Yıldırım"
  | "Edip Yüksel"
  | "Yakub Ibn Nugman"
  | "محمد صالح"
  | "احمد علی"
  | "جالندہری"
  | "علامہ جوادی"
  | "احمد رضا خان"
  | "طاہر القادری"
  | "Мухаммад Содик"
  | "Maududi"
  | "Shakir"
  | "Transliteration"
  | "Cortes"
  | "انصاریان"
  | "القرآن الكريم المبسط (تشكيل بسيط) (simple)"
  | "القرآن الكريم المبسط (بدون تشكيل) (simple-clean)"
  | "القرآن الكريم المبسط (بدون تشكيل) (simple-enhanced)"
  | "القرآن الكريم المبسط (بدون تشكيل) (simple-min)"
  | "القرآن الكريم برسم العثماني (تشكيل بسيط) (uthmani-min)"
  | "القرآن الكريم برسم العثماني (uthmani)"
  | "Теофанов"
  | "Mlivo"
  | "بهرام پور"
  | "Asad"
  | "خرمشاهی"
  | "مجتبوی"
  | "फ़ारूक़ ख़ान & अहमद"
  | "Quraish Shihab"
  | "Basmeih"
  | "Абу Адель"
  | "Крачковский"
  | "Аль-Мунтахаб"
  | "Саблуков"
  | "محمد جوناگڑھی"
  | "ابوالاعلی مودودی"
  | "Ma Jian"
  | "Ma Jian (Traditional)"
  | "خرمدل"
  | "معزی"
  | "Korkut"
  | "تفسير الجلالين"
  | "القرآن الكريم المجود (ملون) (tajweed)"
  | "معاني مفردات القرآن (wordbyword)"
  | "عبد الباسط عبد الصمد المرتل"
  | "عبد الله بصفر"
  | "عبدالرحمن السديس"
  | "عبدالباسط عبدالصمد"
  | "أبو بكر الشاطري"
  | "أحمد بن علي العجمي"
  | "مشاري العفاسي"
  | "هاني الرفاعي"
  | "محمود خليل الحصري"
  | "محمود خليل الحصري (المجود)"
  | "علي بن عبدالرحمن الحذيفي"
  | "إبراهيم الأخضر"
  | "ماهر المعيقلي"
  | "محمد صديق المنشاوي"
  | "محمد صديق المنشاوي (المجود)"
  | "محمد أيوب"
  | "محمد جبريل"
  | "سعود الشريم"
  | "Ibrahim Walk"
  | "Fooladvand - Hedayatfar"
  | "شهریار پرهیزگار"
  | "Shamshad Ali Khan"
  | "中文"
  | "Youssouf Leclerc"
  | "القرآن الكريم للأطفال"
  | "Corpus"
  | "Naseem Ismail"
  | "Buck"
  | "Ma Zhong Gang"
  | "أيمن سويد"
  | "معاني مفردات القرآن ولفظها (wordbyword-2)"
  | "القرآن الكريم برسم العثماني (unicode)"
  | "القرآن الكريم برسم العثماني (quran-academy)"
  | "Kur'an - sa prevodom (značenja) na bosanski jezik, utemeljen na Ibn Kesirovom tumačenju, i kratki komentar"
  | "Elmir Kuliev by 1MuslimApp"
  | "Clear Qur'an - Talal Itani"
  | "تفسير القرطبي"
  | "تنوير المقباس من تفسير بن عباس"
  | "الـتـفـسـيـر الـوسـيـط"
  | "تفسير البغوي"
  | "Ghazi Muhammed Hashim"
  | "Mubarakpuri"
  | "ሳዲቅ & ሳኒ ሐቢብ"
  | "At Mensur"
  | "জহুরুল হক"
  | "Qarai"
  | "Wahiduddin Khan"
  | "Bornez"
  | "Garcia"
  | "محمد حسین نجفی"
  | "قرائتی"
  | "صادقی تهرانی"
  | "صفوی"
  | "Tafsir Jalalayn"
  | "കാരകുന്ന് & എളയാവൂര്"
  | "Leemhuis"
  | "Siregar"
  | "عبدالولي"
  | "Кулиев + ас-Саади"
  | "Elmir Kuliev 2 by 1MuslimApp"
  | "Chechen by Magomedov"
  | "Транскрипция";
