export type SurahNames =
  | "سُورَةُ ٱلْفَاتِحَةِ"
  | "سُورَةُ البَقَرَةِ"
  | "سُورَةُ آلِ عِمۡرَانَ"
  | "سُورَةُ النِّسَاءِ"
  | "سُورَةُ المَائـِدَةِ"
  | "سُورَةُ الأَنۡعَامِ"
  | "سُورَةُ الأَعۡرَافِ"
  | "سُورَةُ الأَنفَالِ"
  | "سُورَةُ التَّوۡبَةِ"
  | "سُورَةُ يُونُسَ"
  | "سُورَةُ هُودٍ"
  | "سُورَةُ يُوسُفَ"
  | "سُورَةُ الرَّعۡدِ"
  | "سُورَةُ إِبۡرَاهِيمَ"
  | "سُورَةُ الحِجۡرِ"
  | "سُورَةُ النَّحۡلِ"
  | "سُورَةُ الإِسۡرَاءِ"
  | "سُورَةُ الكَهۡفِ"
  | "سُورَةُ مَرۡيَمَ"
  | "سُورَةُ طه"
  | "سُورَةُ الأَنبِيَاءِ"
  | "سُورَةُ الحَجِّ"
  | "سُورَةُ المُؤۡمِنُونَ"
  | "سُورَةُ النُّورِ"
  | "سُورَةُ الفُرۡقَانِ"
  | "سُورَةُ الشُّعَرَاءِ"
  | "سُورَةُ النَّمۡلِ"
  | "سُورَةُ القَصَصِ"
  | "سُورَةُ العَنكَبُوتِ"
  | "سُورَةُ الرُّومِ"
  | "سُورَةُ لُقۡمَانَ"
  | "سُورَةُ السَّجۡدَةِ"
  | "سُورَةُ الأَحۡزَابِ"
  | "سُورَةُ سَبَإٍ"
  | "سُورَةُ فَاطِرٍ"
  | "سُورَةُ يسٓ"
  | "سُورَةُ الصَّافَّاتِ"
  | "سُورَةُ صٓ"
  | "سُورَةُ الزُّمَرِ"
  | "سُورَةُ غَافِرٍ"
  | "سُورَةُ فُصِّلَتۡ"
  | "سُورَةُ الشُّورَىٰ"
  | "سُورَةُ الزُّخۡرُفِ"
  | "سُورَةُ الدُّخَانِ"
  | "سُورَةُ الجَاثِيَةِ"
  | "سُورَةُ الأَحۡقَافِ"
  | "سُورَةُ مُحَمَّدٍ"
  | "سُورَةُ الفَتۡحِ"
  | "سُورَةُ الحُجُرَاتِ"
  | "سُورَةُ قٓ"
  | "سُورَةُ الذَّارِيَاتِ"
  | "سُورَةُ الطُّورِ"
  | "سُورَةُ النَّجۡمِ"
  | "سُورَةُ القَمَرِ"
  | "سُورَةُ الرَّحۡمَٰن"
  | "سُورَةُ الوَاقِعَةِ"
  | "سُورَةُ الحَدِيدِ"
  | "سُورَةُ المُجَادلَةِ"
  | "سُورَةُ الحَشۡرِ"
  | "سُورَةُ المُمۡتَحنَةِ"
  | "سُورَةُ الصَّفِّ"
  | "سُورَةُ الجُمُعَةِ"
  | "سُورَةُ المُنَافِقُونَ"
  | "سُورَةُ التَّغَابُنِ"
  | "سُورَةُ الطَّلَاقِ"
  | "سُورَةُ التَّحۡرِيمِ"
  | "سُورَةُ المُلۡكِ"
  | "سُورَةُ القَلَمِ"
  | "سُورَةُ الحَاقَّةِ"
  | "سُورَةُ المَعَارِجِ"
  | "سُورَةُ نُوحٍ"
  | "سُورَةُ الجِنِّ"
  | "سُورَةُ المُزَّمِّلِ"
  | "سُورَةُ المُدَّثِّرِ"
  | "سُورَةُ القِيَامَةِ"
  | "سُورَةُ الإِنسَانِ"
  | "سُورَةُ المُرۡسَلَاتِ"
  | "سُورَةُ النَّبَإِ"
  | "سُورَةُ النَّازِعَاتِ"
  | "سُورَةُ عَبَسَ"
  | "سُورَةُ التَّكۡوِيرِ"
  | "سُورَةُ الانفِطَارِ"
  | "سُورَةُ المُطَفِّفِينَ"
  | "سُورَةُ الانشِقَاقِ"
  | "سُورَةُ البُرُوجِ"
  | "سُورَةُ الطَّارِقِ"
  | "سُورَةُ الأَعۡلَىٰ"
  | "سُورَةُ الغَاشِيَةِ"
  | "سُورَةُ الفَجۡرِ"
  | "سُورَةُ البَلَدِ"
  | "سُورَةُ الشَّمۡسِ"
  | "سُورَةُ اللَّيۡلِ"
  | "سُورَةُ الضُّحَىٰ"
  | "سُورَةُ الشَّرۡحِ"
  | "سُورَةُ التِّينِ"
  | "سُورَةُ العَلَقِ"
  | "سُورَةُ القَدۡرِ"
  | "سُورَةُ البَيِّنَةِ"
  | "سُورَةُ الزَّلۡزَلَةِ"
  | "سُورَةُ العَادِيَاتِ"
  | "سُورَةُ القَارِعَةِ"
  | "سُورَةُ التَّكَاثُرِ"
  | "سُورَةُ العَصۡرِ"
  | "سُورَةُ الهُمَزَةِ"
  | "سُورَةُ الفِيلِ"
  | "سُورَةُ قُرَيۡشٍ"
  | "سُورَةُ المَاعُونِ"
  | "سُورَةُ الكَوۡثَرِ"
  | "سُورَةُ الكَافِرُونَ"
  | "سُورَةُ النَّصۡرِ"
  | "سُورَةُ المَسَدِ"
  | "سُورَةُ الإِخۡلَاصِ"
  | "سُورَةُ الفَلَقِ"
  | "سُورَةُ النَّاسِ";

export type SurahEnglishNames =
  | "Al-Faatiha"
  | "Al-Baqara"
  | "Aal-i-Imraan"
  | "An-Nisaa"
  | "Al-Maaida"
  | "Al-An'aam"
  | "Al-A'raaf"
  | "Al-Anfaal"
  | "At-Tawba"
  | "Yunus"
  | "Hud"
  | "Yusuf"
  | "Ar-Ra'd"
  | "Ibrahim"
  | "Al-Hijr"
  | "An-Nahl"
  | "Al-Israa"
  | "Al-Kahf"
  | "Maryam"
  | "Taa-Haa"
  | "Al-Anbiyaa"
  | "Al-Hajj"
  | "Al-Muminoon"
  | "An-Noor"
  | "Al-Furqaan"
  | "Ash-Shu'araa"
  | "An-Naml"
  | "Al-Qasas"
  | "Al-Ankaboot"
  | "Ar-Room"
  | "Luqman"
  | "As-Sajda"
  | "Al-Ahzaab"
  | "Saba"
  | "Faatir"
  | "Yaseen"
  | "As-Saaffaat"
  | "Saad"
  | "Az-Zumar"
  | "Ghafir"
  | "Fussilat"
  | "Ash-Shura"
  | "Az-Zukhruf"
  | "Ad-Dukhaan"
  | "Al-Jaathiya"
  | "Al-Ahqaf"
  | "Muhammad"
  | "Al-Fath"
  | "Al-Hujuraat"
  | "Qaaf"
  | "Adh-Dhaariyat"
  | "At-Tur"
  | "An-Najm"
  | "Al-Qamar"
  | "Ar-Rahmaan"
  | "Al-Waaqia"
  | "Al-Hadid"
  | "Al-Mujaadila"
  | "Al-Hashr"
  | "Al-Mumtahana"
  | "As-Saff"
  | "Al-Jumu'a"
  | "Al-Munaafiqoon"
  | "At-Taghaabun"
  | "At-Talaaq"
  | "At-Tahrim"
  | "Al-Mulk"
  | "Al-Qalam"
  | "Al-Haaqqa"
  | "Al-Ma'aarij"
  | "Nooh"
  | "Al-Jinn"
  | "Al-Muzzammil"
  | "Al-Muddaththir"
  | "Al-Qiyaama"
  | "Al-Insaan"
  | "Al-Mursalaat"
  | "An-Naba"
  | "An-Naazi'aat"
  | "Abasa"
  | "At-Takwir"
  | "Al-Infitaar"
  | "Al-Mutaffifin"
  | "Al-Inshiqaaq"
  | "Al-Burooj"
  | "At-Taariq"
  | "Al-A'laa"
  | "Al-Ghaashiya"
  | "Al-Fajr"
  | "Al-Balad"
  | "Ash-Shams"
  | "Al-Lail"
  | "Ad-Dhuhaa"
  | "Ash-Sharh"
  | "At-Tin"
  | "Al-Alaq"
  | "Al-Qadr"
  | "Al-Bayyina"
  | "Az-Zalzala"
  | "Al-Aadiyaat"
  | "Al-Qaari'a"
  | "At-Takaathur"
  | "Al-Asr"
  | "Al-Humaza"
  | "Al-Fil"
  | "Quraish"
  | "Al-Maa'un"
  | "Al-Kawthar"
  | "Al-Kaafiroon"
  | "An-Nasr"
  | "Al-Masad"
  | "Al-Ikhlaas"
  | "Al-Falaq"
  | "An-Naas";
export type SurahEnglishNameTranslation =
  | "The Opening"
  | "The Cow"
  | "The Family of Imraan"
  | "The Women"
  | "The Table"
  | "The Cattle"
  | "The Heights"
  | "The Spoils of War"
  | "The Repentance"
  | "Jonas"
  | "Hud"
  | "Joseph"
  | "The Thunder"
  | "Abraham"
  | "The Rock"
  | "The Bee"
  | "The Night Journey"
  | "The Cave"
  | "Mary"
  | "Taa-Haa"
  | "The Prophets"
  | "The Pilgrimage"
  | "The Believers"
  | "The Light"
  | "The Criterion"
  | "The Poets"
  | "The Ant"
  | "The Stories"
  | "The Spider"
  | "The Romans"
  | "Luqman"
  | "The Prostration"
  | "The Clans"
  | "Sheba"
  | "The Originator"
  | "Yaseen"
  | "Those drawn up in Ranks"
  | "The letter Saad"
  | "The Groups"
  | "The Forgiver"
  | "Explained in detail"
  | "Consultation"
  | "Ornaments of gold"
  | "The Smoke"
  | "Crouching"
  | "The Dunes"
  | "Muhammad"
  | "The Victory"
  | "The Inner Apartments"
  | "The letter Qaaf"
  | "The Winnowing Winds"
  | "The Mount"
  | "The Star"
  | "The Moon"
  | "The Beneficent"
  | "The Inevitable"
  | "The Iron"
  | "The Pleading Woman"
  | "The Exile"
  | "She that is to be examined"
  | "The Ranks"
  | "Friday"
  | "The Hypocrites"
  | "Mutual Disillusion"
  | "Divorce"
  | "The Prohibition"
  | "The Sovereignty"
  | "The Pen"
  | "The Reality"
  | "The Ascending Stairways"
  | "Noah"
  | "The Jinn"
  | "The Enshrouded One"
  | "The Cloaked One"
  | "The Resurrection"
  | "Man"
  | "The Emissaries"
  | "The Announcement"
  | "Those who drag forth"
  | "He frowned"
  | "The Overthrowing"
  | "The Cleaving"
  | "Defrauding"
  | "The Splitting Open"
  | "The Constellations"
  | "The Morning Star"
  | "The Most High"
  | "The Overwhelming"
  | "The Dawn"
  | "The City"
  | "The Sun"
  | "The Night"
  | "The Morning Hours"
  | "The Consolation"
  | "The Fig"
  | "The Clot"
  | "The Power, Fate"
  | "The Evidence"
  | "The Earthquake"
  | "The Chargers"
  | "The Calamity"
  | "Competition"
  | "The Declining Day, Epoch"
  | "The Traducer"
  | "The Elephant"
  | "Quraysh"
  | "Almsgiving"
  | "Abundance"
  | "The Disbelievers"
  | "Divine Support"
  | "The Palm Fibre"
  | "Sincerity"
  | "The Dawn"
  | "Mankind";


export type SurahRevelationType = "Meccan" | "Medinan";