export type QuranNameText =
  | "تفسير المیسر"
  | "Məmmədəliyev & Bünyadov"
  | "Musayev"
  | "মুহিউদ্দীন খান"
  | "Hrbek"
  | "Nykl"
  | "Abu Rida"
  | "Bubenheim & Elyas"
  | "Khoury"
  | "Zaidan"
  | "ދިވެހި"
  | "Ahmed Ali"
  | "Ahmed Raza Khan"
  | "Arberry"
  | "Asad"
  | "Daryabadi"
  | "Hilali & Khan"
  | "Pickthall"
  | "Qaribullah & Darwish"
  | "Saheeh International"
  | "Sarwar"
  | "Yusuf Ali"
  | "آیتی"
  | "فولادوند"
  | "الهی قمشه‌ای"
  | "مکارم شیرازی"
  | "Hamidullah"
  | "Gumi"
  | "फ़ारूक़ ख़ान & नदवी"
  | "Bahasa Indonesia"
  | "Piccardo"
  | "Japanese"
  | "Korean"
  | "ته‌فسیری ئاسان"
  | "അബ്ദുല്‍ ഹമീദ് & പറപ്പൂര്‍"
  | "Keyzer"
  | "Einar Berg"
  | "Bielawskiego"
  | "El-Hayek"
  | "Grigore"
  | "Кулиев"
  | "Османов"
  | "Порохова"
  | "امروٽي"
  | "Abduh"
  | "Sherif Ahmeti"
  | "Feti Mehdiu"
  | "Efendi Nahi"
  | "Bernström"
  | "Al-Barwani"
  | "ஜான் டிரஸ்ட்"
  | "Оятӣ"
  | "ภาษาไทย"
  | "Süleyman Ateş"
  | "Alİ Bulaç"
  | "Diyanet İşleri"
  | "Abdulbakî Gölpınarlı"
  | "Öztürk"
  | "Çeviriyazı"
  | "Diyanet Vakfı"
  | "Elmalılı Hamdi Yazır"
  | "Suat Yıldırım"
  | "Edip Yüksel"
  | "Yakub Ibn Nugman"
  | "محمد صالح"
  | "احمد علی"
  | "جالندہری"
  | "علامہ جوادی"
  | "احمد رضا خان"
  | "طاہر القادری"
  | "Мухаммад Содик"
  | "Maududi"
  | "Shakir"
  | "Transliteration"
  | "Cortes"
  | "انصاریان"
  | "القرآن الكريم المبسط (تشكيل بسيط) (simple)"
  | "القرآن الكريم المبسط (بدون تشكيل) (simple-clean)"
  | "القرآن الكريم المبسط (بدون تشكيل) (simple-enhanced)"
  | "القرآن الكريم المبسط (بدون تشكيل) (simple-min)"
  | "القرآن الكريم برسم العثماني (تشكيل بسيط) (uthmani-min)"
  | "القرآن الكريم برسم العثماني (uthmani)"
  | "Теофанов"
  | "Mlivo"
  | "بهرام پور"
  | "Asad"
  | "خرمشاهی"
  | "مجتبوی"
  | "फ़ारूक़ ख़ान & अहमद"
  | "Quraish Shihab"
  | "Basmeih"
  | "Абу Адель"
  | "Крачковский"
  | "Аль-Мунтахаб"
  | "Саблуков"
  | "محمد جوناگڑھی"
  | "ابوالاعلی مودودی"
  | "Ma Jian"
  | "Ma Jian (Traditional)"
  | "خرمدل"
  | "معزی"
  | "Korkut"
  | "تفسير الجلالين"
  | "القرآن الكريم المجود (ملون) (tajweed)"
  | "معاني مفردات القرآن (wordbyword)"
  | "القرآن الكريم للأطفال"
  | "Corpus"
  | "Naseem Ismail"
  | "Buck"
  | "Ma Zhong Gang"
  | "معاني مفردات القرآن ولفظها (wordbyword-2)"
  | "القرآن الكريم برسم العثماني (unicode)"
  | "القرآن الكريم برسم العثماني (quran-academy)"
  | "Kur'an - sa prevodom (značenja) na bosanski jezik, utemeljen na Ibn Kesirovom tumačenju, i kratki komentar"
  | "Clear Qur'an - Talal Itani"
  | "تفسير القرطبي"
  | "تنوير المقباس من تفسير بن عباس"
  | "الـتـفـسـيـر الـوسـيـط"
  | "تفسير البغوي"
  | "Ghazi Muhammed Hashim"
  | "Mubarakpuri"
  | "ሳዲቅ & ሳኒ ሐቢብ"
  | "At Mensur"
  | "জহুরুল হক"
  | "Qarai"
  | "Wahiduddin Khan"
  | "Bornez"
  | "Garcia"
  | "محمد حسین نجفی"
  | "قرائتی"
  | "صادقی تهرانی"
  | "صفوی"
  | "Tafsir Jalalayn"
  | "കാരകുന്ന് & എളയാവൂര്"
  | "Leemhuis"
  | "Siregar"
  | "عبدالولي"
  | "Кулиев + ас-Саади"
  | "Chechen by Magomedov"
  | "Транскрипция";







export type QuranEnglishName = 
| "King Fahad Quran Complex"
| "Vasim Mammadaliyev and Ziya Bunyadov"
| "Alikhan Musayev"
| "Muhiuddin Khan"
| "Preklad I. Hrbek"
| "A. R. Nykl"
| "Abu Rida Muhammad ibn Ahmad ibn Rassoul"
| "A. S. F. Bubenheim and N. Elyas"
| "Adel Theodor Khoury"
| "Amir Zaidan"
| "Office of the President of Maldives"
| "Ahmed Ali"
| "Ahmed Raza Khan"
| "A. J. Arberry"
| "Muhammad Asad"
| "Abdul Majid Daryabadi"
| "Muhammad Taqi-ud-Din al-Hilali and Muhammad Muhsin Khan"
| "Mohammed Marmaduke William Pickthall"
| "Hasan al-Fatih Qaribullah and Ahmad Darwish"
| "Saheeh International"
| "Muhammad Sarwar"
| "Abdullah Yusuf Ali"
| "AbdolMohammad Ayati"
| "Mohammad Mahdi Fooladvand"
| "Mahdi Elahi Ghomshei"
| "Naser Makarem Shirazi"
| "Muhammad Hamidullah"
| "Abubakar Mahmoud Gumi"
| "Suhel Farooq Khan and Saifur Rahman Nadwi"
| "Unknown"
| "Hamza Roberto Piccardo"
| "Unknown"
| "Unknown"
| "Burhan Muhammad-Amin"
| "Cheriyamundam Abdul Hameed and Kunhi Mohammed Parappoor"
| "Salomo Keyzer"
| "Einar Berg"
| "Józefa Bielawskiego"
| "Samir El-Hayek"
| "George Grigore"
| "Elmir Kuliev"
| "Magomed-Nuri Osmanovich Osmanov"
| "V. Porokhova"
| "Taj Mehmood Amroti"
| "Mahmud Muhammad Abduh"
| "Sherif Ahmeti"
| "Feti Mehdiu"
| "Hasan Efendi Nahi"
| "Knut Bernström"
| "Ali Muhsin Al-Barwani"
| "Jan Turst Foundation"
| "AbdolMohammad Ayati"
| "King Fahad Quran Complex"
| "Suleyman Ates"
| "Alİ Bulaç"
| "Diyanet Isleri"
| "Abdulbaki Golpinarli"
| "Yasar Nuri Ozturk"
| "Muhammet Abay"
| "Diyanet Vakfi"
| "Elmalili Hamdi Yazir"
| "Suat Yildirim"
| "Edip Yüksel"
| "Yakub Ibn Nugman"
| "Muhammad Saleh"
| "Ahmed Ali"
| "Fateh Muhammad Jalandhry"
| "Syed Zeeshan Haider Jawadi"
| "Ahmed Raza Khan"
| "Tahir ul Qadri"
| "Muhammad Sodik Muhammad Yusuf"
| "Abul Ala Maududi"
| "Mohammad Habib Shakir"
| "English Transliteration"
| "Julio Cortes"
| "Hussain Ansarian"
| "Simple"
| "Simple Clean"
| "Simple Enhanced"
| "Simple Minimal"
| "Uthmani Minimal"
| "Uthmani"
| "Tzvetan Theophanov"
| "Mustafa Mlivo"
| "Abolfazl Bahrampour"
| "Muhammad Asad - Abdurrasak Pérez"
| "Baha'oddin Khorramshahi"
| "Sayyed Jalaloddin Mojtabavi"
| "Muhammad Farooq Khan and Muhammad Ahmed"
| "Muhammad Quraish Shihab et al."
| "Abdullah Muhammad Basmeih"
| "Abu Adel"
| "Ignaty Yulianovich Krachkovsky"
| "Ministry of Awqaf, Egypt"
| "Gordy Semyonovich Sablukov"
| "Muhammad Junagarhi"
| "Abul A'ala Maududi"
| "Ma Jian"
| "Ma Jian"
| "Mostafa Khorramdel"
| "Mohammad Kazem Moezzi"
| "Besim Korkut"
| "Jalal ad-Din al-Mahalli and Jalal ad-Din as-Suyuti"
| "Tajweed"
| "Word By Word"
| "Kids"
| "Corpus"
| "Naseem Isamil and Masoor Maulana, Kaleel"
| "Buck"
| "马仲刚"
| "Word by Word Transaltion by Dr. Shehnaz Shaikh"
| "Unicode Quran text from Khaled Hosny"
| "Modified Quran Uthmani Text from the Quran Academy to work with the Kitab font"
| "Quran translation by Muhamed Mehanovic"
| "Clear Qur'an by Talal Itani"
| "Tafseer Al Qurtubi"
| "Tafseer Tanwir al-Miqbas"
| "Tafseer Al-Waseet"
| "Tafseer Al-Baghawi"
| "Translation by Ghazi Muhammed Hashim"
| "Mubarakpuri"
| "ሳዲቅ & ሳኒ ሐቢብ"
| "At Mensur"
| "জহুরুল হক"
| "Qarai"
| "Wahiduddin Khan"
| "Bornez"
| "Garcia"
| "محمد حسین نجفی"
| "قرائتی"
| "صادقی تهرانی"
| "صفوی"
| "Tafsir Jalalayn"
| "കാരകുന്ന് & എളയാവൂര്"
| "Leemhuis"
| "Siregar"
| "عبدالولي"
| "Кулиев + ас-Саади"
| "Chechen by Magomedov"
| "Russian Transliteration"

export type QuranIdentifierText = 
| "ar.muyassar"    
| "az.mammadaliyev"
| "az.musayev"     
| "bn.bengali"     
| "cs.hrbek"       
| "cs.nykl"        
| "de.aburida"     
| "de.bubenheim"   
| "de.khoury"      
| "de.zaidan"      
| "dv.divehi"      
| "en.ahmedali"    
| "en.ahmedraza"   
| "en.arberry"     
| "en.asad"
| "en.daryabadi"
| "en.hilali"
| "en.pickthall"
| "en.qaribullah"
| "en.sahih"
| "en.sarwar"
| "en.yusufali"
| "fa.ayati"
| "fa.fooladvand"
| "fa.ghomshei"
| "fa.makarem"
| "fr.hamidullah"
| "ha.gumi"
| "hi.hindi"
| "id.indonesian"
| "it.piccardo"
| "ja.japanese"
| "ko.korean"
| "ku.asan"
| "ml.abdulhameed"
| "nl.keyzer"
| "no.berg"
| "pl.bielawskiego"
| "pt.elhayek"
| "ro.grigore"
| "ru.kuliev"
| "ru.osmanov"
| "ru.porokhova"
| "sd.amroti"
| "so.abduh"
| "sq.ahmeti"
| "sq.mehdiu"
| "sq.nahi"
| "sv.bernstrom"
| "sw.barwani"
| "ta.tamil"
| "tg.ayati"
| "th.thai"
| "tr.ates"
| "tr.bulac"
| "tr.diyanet"
| "tr.golpinarli"
| "tr.ozturk"
| "tr.transliteration"
| "tr.vakfi"
| "tr.yazir"
| "tr.yildirim"
| "tr.yuksel"
| "tt.nugman"
| "ug.saleh"
| "ur.ahmedali"
| "ur.jalandhry"
| "ur.jawadi"
| "ur.kanzuliman"
| "ur.qadri"
| "uz.sodik"
| "en.maududi"
| "en.shakir"
| "en.transliteration"
| "es.cortes"
| "fa.ansarian"
| "quran-simple"
| "quran-simple-clean"
| "quran-simple-enhanced"
| "quran-simple-min"
| "quran-uthmani-min"
| "quran-uthmani"
| "bg.theophanov"
| "bs.mlivo"
| "fa.bahrampour"
| "es.asad"
| "fa.khorramshahi"
| "fa.mojtabavi"
| "hi.farooq"
| "id.muntakhab"
| "ms.basmeih"
| "ru.abuadel"
| "ru.krachkovsky"
| "ru.muntahab"
| "ru.sablukov"
| "ur.junagarhi"
| "ur.maududi"
| "zh.jian"
| "zh.majian"
| "fa.khorramdel"
| "fa.moezzi"
| "bs.korkut"
| "ar.jalalayn"
| "quran-tajweed"
| "quran-wordbyword"
| "quran-kids"
| "quran-corpus-qd"
| "si.naseemismail"
| "quran-buck"
| "zh.mazhonggang"
| "quran-wordbyword-2"
| "quran-unicode"
| "quran-uthmani-quran-academy"
| "ba.mehanovic"
| "en.itani"
| "ar.qurtubi"
| "ar.miqbas"
| "ar.waseet"
| "ar.baghawi"
| "my.ghazi"
| "en.mubarakpuri"
| "am.sadiq"
| "ber.mensur"
| "bn.hoque"
| "en.qarai"
| "en.wahiduddin"
| "es.bornez"
| "es.garcia"
| "ur.najafi"
| "fa.gharaati"
| "fa.sadeqi"
| "fa.safavi"
| "id.jalalayn"
| "ml.karakunnu"
| "nl.leemhuis"
| "nl.siregar"
| "ps.abdulwali"
| "ru.kuliev-alsaadi"
| "ce.magomedov"
| "ru.transliteration"


export type QuranLanguageText =
  | "ar"
  | "az"
  | "bn"
  | "cs"
  | "de"
  | "dv"
  | "en"
  | "fa"
  | "fr"
  | "ha"
  | "hi"
  | "id"
  | "it"
  | "ja"
  | "ko"
  | "ku"
  | "ml"
  | "nl"
  | "no"
  | "pl"
  | "pt"
  | "ro"
  | "ru"
  | "sd"
  | "so"
  | "sq"
  | "sv"
  | "sw"
  | "ta"
  | "tg"
  | "th"
  | "tr"
  | "tt"
  | "ug"
  | "ur"
  | "uz"
  | "es"
  | "bg"
  | "bs"
  | "ms"
  | "zh"
  | "si"
  | "ba"
  | "my"
  | "am"
  | "ber"
  | "ps"
  | "ce";