/** @private */
const identifierByName = {
"تفسير المیسر": "ar.muyassar",
"Məmmədəliyev & Bünyadov": "az.mammadaliyev",
"Musayev": "az.musayev",
"মুহিউদ্দীন খান": "bn.bengali",
"Hrbek": "cs.hrbek",
"Nykl": "cs.nykl",
"Abu Rida": "de.aburida",
"Bubenheim & Elyas": "de.bubenheim",
"Khoury": "de.khoury",
"Zaidan": "de.zaidan",
"ދިވެހި": "dv.divehi",
"Ahmed Ali": "en.ahmedali",
"Ahmed Raza Khan": "en.ahmedraza",
"Arberry": "en.arberry",
"Asad": "en.asad",
"Daryabadi": "en.daryabadi",
"Hilali & Khan": "en.hilali",
"Pickthall": "en.pickthall",
"Qaribullah & Darwish": "en.qaribullah",
"Saheeh International": "en.sahih",
"Sarwar": "en.sarwar",
"Yusuf Ali": "en.yusufali",
"آیتی": "fa.ayati",
"فولادوند": "fa.fooladvand",
"الهی قمشه‌ای": "fa.ghomshei",
"مکارم شیرازی": "fa.makarem",
"Hamidullah": "fr.hamidullah",
"Gumi": "ha.gumi",
"फ़ारूक़ ख़ान & नदवी": "hi.hindi",
"Bahasa Indonesia": "id.indonesian",
"Piccardo": "it.piccardo",
"Japanese": "ja.japanese",
"Korean": "ko.korean",
"ته‌فسیری ئاسان": "ku.asan",
"അബ്ദുല്‍ ഹമീദ് & പറപ്പൂര്‍": "ml.abdulhameed",
"Keyzer": "nl.keyzer",
"Einar Berg": "no.berg",
"Bielawskiego": "pl.bielawskiego",
"El-Hayek": "pt.elhayek",
"Grigore": "ro.grigore",
"Кулиев": "ru.kuliev",
"Османов": "ru.osmanov",
"Порохова": "ru.porokhova",
"امروٽي": "sd.amroti",
"Abduh": "so.abduh",
"Sherif Ahmeti": "sq.ahmeti",
"Feti Mehdiu": "sq.mehdiu",
"Efendi Nahi": "sq.nahi",
"Bernström": "sv.bernstrom",
"Al-Barwani": "sw.barwani",
"ஜான் டிரஸ்ட்": "ta.tamil",
"Оятӣ": "tg.ayati",
"ภาษาไทย": "th.thai",
"Süleyman Ateş": "tr.ates",
"Alİ Bulaç": "tr.bulac",
"Diyanet İşleri": "tr.diyanet",
"Abdulbakî Gölpınarlı": "tr.golpinarli",
"Öztürk": "tr.ozturk",
"Çeviriyazı": "tr.transliteration",
"Diyanet Vakfı": "tr.vakfi",
"Elmalılı Hamdi Yazır": "tr.yazir",
"Suat Yıldırım": "tr.yildirim",
"Edip Yüksel": "tr.yuksel",
"Yakub Ibn Nugman": "tt.nugman",
"محمد صالح": "ug.saleh",
"احمد علی": "ur.ahmedali",
"جالندہری": "ur.jalandhry",
"علامہ جوادی": "ur.jawadi",
"احمد رضا خان": "ur.kanzuliman",
"طاہر القادری": "ur.qadri",
"Мухаммад Содик": "uz.sodik",
"Maududi": "en.maududi",
"Shakir": "en.shakir",
"Transliteration": "en.transliteration",
"Cortes": "es.cortes",
"انصاریان": "fa.ansarian",
"القرآن الكريم المبسط (تشكيل بسيط) (simple)": "quran-simple",
"القرآن الكريم المبسط (بدون تشكيل) (simple-clean)": "quran-simple-clean",
"القرآن الكريم المبسط (بدون تشكيل) (simple-enhanced)": "quran-simple-enhanced",
"القرآن الكريم المبسط (بدون تشكيل) (simple-min)": "quran-simple-min",
"القرآن الكريم برسم العثماني (تشكيل بسيط) (uthmani-min)": "quran-uthmani-min",
"القرآن الكريم برسم العثماني (uthmani)": "quran-uthmani",
"Теофанов": "bg.theophanov",
"Mlivo": "bs.mlivo",
"بهرام پور": "fa.bahrampour",
"Asad": "es.asad",
"خرمشاهی": "fa.khorramshahi",
"مجتبوی": "fa.mojtabavi",
"फ़ारूक़ ख़ान & अहमद": "hi.farooq",
"Quraish Shihab": "id.muntakhab",
"Basmeih": "ms.basmeih",
"Абу Адель": "ru.abuadel",
"Крачковский": "ru.krachkovsky",
"Аль-Мунтахаб": "ru.muntahab",
"Саблуков": "ru.sablukov",
"محمد جوناگڑھی": "ur.junagarhi",
"ابوالاعلی مودودی": "ur.maududi",
"Ma Jian": "zh.jian",
"Ma Jian (Traditional)": "zh.majian",
"خرمدل": "fa.khorramdel",
"معزی": "fa.moezzi",
"Korkut": "bs.korkut",
"تفسير الجلالين": "ar.jalalayn",
"القرآن الكريم المجود (ملون) (tajweed)": "quran-tajweed",
"معاني مفردات القرآن (wordbyword)": "quran-wordbyword",
"عبد الباسط عبد الصمد المرتل": "ar.abdulbasitmurattal",
"عبد الله بصفر": "ar.abdullahbasfar",
"عبدالرحمن السديس": "ar.abdurrahmaansudais",
"عبدالباسط عبدالصمد": "ar.abdulsamad",
"أبو بكر الشاطري": "ar.shaatree",
"أحمد بن علي العجمي": "ar.ahmedajamy",
"مشاري العفاسي": "ar.alafasy",
"هاني الرفاعي": "ar.hanirifai",
"محمود خليل الحصري": "ar.husary",
"محمود خليل الحصري (المجود)": "ar.husarymujawwad",
"علي بن عبدالرحمن الحذيفي": "ar.hudhaify",
"إبراهيم الأخضر": "ar.ibrahimakhbar",
"ماهر المعيقلي": "ar.mahermuaiqly",
"محمد صديق المنشاوي": "ar.minshawi",
"محمد صديق المنشاوي (المجود)": "ar.minshawimujawwad",
"محمد أيوب": "ar.muhammadayyoub",
"محمد جبريل": "ar.muhammadjibreel",
"سعود الشريم": "ar.saoodshuraym",
"Ibrahim Walk": "en.walk",
"Fooladvand - Hedayatfar": "fa.hedayatfarfooladvand",
"شهریار پرهیزگار": "ar.parhizgar",
"Shamshad Ali Khan": "ur.khan",
"中文": "zh.chinese",
"Youssouf Leclerc": "fr.leclerc",
"القرآن الكريم للأطفال": "quran-kids",
"Corpus": "quran-corpus-qd",
"Naseem Ismail": "si.naseemismail",
"Buck": "quran-buck",
"Ma Zhong Gang": "zh.mazhonggang",
"أيمن سويد": "ar.aymanswoaid",
"معاني مفردات القرآن ولفظها (wordbyword-2)": "quran-wordbyword-2",
"القرآن الكريم برسم العثماني (unicode)": "quran-unicode",
"القرآن الكريم برسم العثماني (quran-academy)": "quran-uthmani-quran-academy",
"Kur'an - sa prevodom (značenja) na bosanski jezik, utemeljen na Ibn Kesirovom tumačenju, i kratki komentar": "ba.mehanovic",
"Elmir Kuliev by 1MuslimApp": "ru.kuliev-audio",
"Clear Qur'an - Talal Itani": "en.itani",
"تفسير القرطبي": "ar.qurtubi",
"تنوير المقباس من تفسير بن عباس": "ar.miqbas",
"الـتـفـسـيـر الـوسـيـط": "ar.waseet",
"تفسير البغوي": "ar.baghawi",
"Ghazi Muhammed Hashim": "my.ghazi",
"Mubarakpuri": "en.mubarakpuri",
"ሳዲቅ & ሳኒ ሐቢብ": "am.sadiq",
"At Mensur": "ber.mensur",
"জহুরুল হক": "bn.hoque",
"Qarai": "en.qarai",
"Wahiduddin Khan": "en.wahiduddin",
"Bornez": "es.bornez",
"Garcia": "es.garcia",
"محمد حسین نجفی": "ur.najafi",
"قرائتی": "fa.gharaati",
"صادقی تهرانی": "fa.sadeqi",
"صفوی": "fa.safavi",
"Tafsir Jalalayn": "id.jalalayn",
"കാരകുന്ന് & എളയാവൂര്": "ml.karakunnu",
"Leemhuis": "nl.leemhuis",
"Siregar": "nl.siregar",
"عبدالولي": "ps.abdulwali",
"Кулиев + ас-Саади": "ru.kuliev-alsaadi",
"Elmir Kuliev 2 by 1MuslimApp": "ru.kuliev-audio-2",
"Chechen by Magomedov": "ce.magomedov",
"Транскрипция": "ru.transliteration",
};
/** @private */
module.exports = identifierByName;