import { TextEdition,QuranIdentifierText,QuranFullText,SurahNames,SurahText,QuranAdvancedOptions } from './../quran';
type ar_QuranTextNames = 
| "تفسير المیسر"
| "القرآن الكريم المبسط (تشكيل بسيط) (simple)"
| "القرآن الكريم المبسط (بدون تشكيل) (simple-clean)"      
| "القرآن الكريم المبسط (بدون تشكيل) (simple-enhanced)"   
| "القرآن الكريم المبسط (بدون تشكيل) (simple-min)"        
| "القرآن الكريم برسم العثماني (تشكيل بسيط) (uthmani-min)"
| "القرآن الكريم برسم العثماني (uthmani)"
| "تفسير الجلالين"
| "القرآن الكريم المجود (ملون) (tajweed)"
| "معاني مفردات القرآن (wordbyword)"
| "القرآن الكريم للأطفال"
| "Corpus"
| "Buck"
| "معاني مفردات القرآن ولفظها (wordbyword-2)"
| "القرآن الكريم برسم العثماني (unicode)"
| "القرآن الكريم برسم العثماني (quran-academy)"
| "تفسير القرطبي"
| "تنوير المقباس من تفسير بن عباس"
| "الـتـفـسـيـر الـوسـيـط"
| "تفسير البغوي";
export interface QuranTextNamesByLanguage {
   "ar":ar_QuranTextNames;
   "az":""
   "bn":""
   "cs":""
   "de":""
   "dv":""
   "en":""
   "fa":""
   "fr":""
   "ha":""
   "hi":""
   "id":""
   "it":""
   "ja":""
   "ko":""
   "ku":""
   "ml":""
   "nl":""
   "no":""
   "pl":""
   "pt":""
   "ro":""
   "ru":""
   "sd":""
   "so":""
   "sq":""
   "sv":""
   "sw":""
   "ta":""
   "tg":""
   "th":""
   "tr":""
   "tt":""
   "ug":""
   "ur":""
   "uz":""
   "es":""
   "bg":""
   "bs":""
   "ms":""
   "zh":""
   "si":""
   "ba":""
   "my":""
   "am":""
   "ber":""
   "ps":""
   "ce":""
}

